# Import classes of attributes
from Rectangle import Rectangle
from Circle import Circle

class Cylinder:
    """A ruled surface generated by a uniparametric family of parallel lines

    Attributes:
        __rectangle: Rectangle
        __circle: Circle
        
    Methods:
        area
    """

    __rectangle: Rectangle
    __circle: Circle

    def __init__(self, circle: Circle, rectangle: Rectangle) -> None:
        """Creates a cylinder object

        Args:
            circle (Circle): _description_ Superior or inferior circle of cylinder
            rectangle (Rectangle): _description_ Cylinder side cover
        """
        # Initializes attributes
        self.__circle = circle
        self.__rectangle = rectangle

    def area(self) -> float:
        """Returns the area of cylinder

        Returns:
            float: _description_ area
        """
        return 2 * self.__circle.area() + self.__rectangle.area()